#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
#     (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#         noncompliant, but you have some other compliant shell such as ksh or
#         bash, then to run this script, type that shell name before the whole
#         command line, like:
#
#         ksh Gradle
#
#         Busybox and similar reduced shells will NOT work, because this script
#         requires all of these POSIX shell features:
#           * functions;
#           * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#             «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#           * compound commands having a testable exit status, especially «case»;
#           * various built-in commands including «command», «set», and «ulimit».
#
#     (2) This script targets any POSIX shell, so it avoids extensions provided
#         by Bash, Ksh, etc; in particular arrays are avoided.
#
# The "traditional" practice of packing binary data into shell scripts is abused
# here (for speed), but should be updated to a more modern implementation if
# necessary.
#

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

APP_HOME=$( cd "${0%/*}" 2>/dev/null && pwd )

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

exec "$JAVACMD" "$@"
